<script lang="ts">
	import {
		type PaletteInputs,
		type ThemePalette,
		generateBaseScale,
		generateFullPalette,
		oklchToCssString,
		oklchToHex,
		BASE_LIGHTNESS_LIGHT_RANGE,
		BASE_LIGHTNESS_DARK_RANGE,
		DEFAULT_INPUTS
	} from '../../../utils/oklch';
	import { createTranslator, type ToolLang } from '../../../i18n/tools';
	import ColorField from './ColorField.svelte';
	import DummyGraphPage from './DummyGraphPage.svelte';
	import Icon from '../shared/Icon.svelte';

	interface Props {
		lang: ToolLang;
	}

	let { lang }: Props = $props();
	// `$derived`, not a plain const: the const would capture only the initial
	// `lang`. Each route passes a fixed locale today, so this never actually
	// recomputes — but the reactive form is the one that stays correct.
	let t = $derived(createTranslator(lang));

	// ── CSS export template ────────────────────────────────────────────────────

	const generateThemeCssContent = (light: ThemePalette, dark: ThemePalette): string => {
		return `/*
 * modernGraphTool — Theme Variables
 * Generated by Theme Generator
 *
 * Graph variables control D3.js SVG rendering where Tailwind classes cannot be used.
 * Base variables follow DaisyUI naming — all UI chrome is derived via opacity modifiers.
 * All variables switch automatically between light and dark mode.
 */

:root {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-bg: ${light.graphBg};
\t--color-graph-watermark-opacity: ${light.graphWatermarkOpacity};
\t--color-graph-grid-major: ${light.graphGridMajor};
\t--color-graph-grid-minor: ${light.graphGridMinor};
\t--color-graph-axis-label: ${light.graphAxisLabel};
\t--color-graph-grid-text: ${light.graphGridText};
\t--color-graph-baseline: ${light.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${light.base100};
\t--color-base-200: ${light.base200};
\t--color-base-300: ${light.base300};
\t--color-base-content: ${light.baseContent};
\t--color-primary: ${light.primary};
\t--color-primary-content: ${light.primaryContent};
\t--color-secondary: ${light.secondary};
\t--color-secondary-content: ${light.secondaryContent};
\t--color-accent: ${light.accent};
\t--color-accent-content: ${light.accentContent};
\t--color-neutral: ${light.neutral};
\t--color-neutral-content: ${light.neutralContent};
\t--color-info: ${light.info};
\t--color-info-content: ${light.infoContent};
\t--color-success: ${light.success};
\t--color-success-content: ${light.successContent};
\t--color-warning: ${light.warning};
\t--color-warning-content: ${light.warningContent};
\t--color-error: ${light.error};
\t--color-error-content: ${light.errorContent};
}

.dark {
\t/* ── Graph ─────────────────────────────────────────────────────────── */
\t--color-graph-grid-major: ${dark.graphGridMajor};
\t--color-graph-grid-minor: ${dark.graphGridMinor};
\t--color-graph-axis-label: ${dark.graphAxisLabel};
\t--color-graph-grid-text: ${dark.graphGridText};
\t--color-graph-baseline: ${dark.graphBaseline};

\t/* ── Base ──────────────────────────────────────────────────────────── */
\t--color-base-100: ${dark.base100};
\t--color-base-200: ${dark.base200};
\t--color-base-300: ${dark.base300};
\t--color-base-content: ${dark.baseContent};
\t--color-primary: ${dark.primary};
\t--color-primary-content: ${dark.primaryContent};
\t--color-secondary: ${dark.secondary};
\t--color-secondary-content: ${dark.secondaryContent};
\t--color-accent: ${dark.accent};
\t--color-accent-content: ${dark.accentContent};
\t--color-neutral: ${dark.neutral};
\t--color-neutral-content: ${dark.neutralContent};
\t--color-info: ${dark.info};
\t--color-info-content: ${dark.infoContent};
\t--color-success: ${dark.success};
\t--color-success-content: ${dark.successContent};
\t--color-warning: ${dark.warning};
\t--color-warning-content: ${dark.warningContent};
\t--color-error: ${dark.error};
\t--color-error-content: ${dark.errorContent};
}
`;
	};

	// ── Random color generation helpers ────────────────────────────────────────

	function randomHex(): string {
		return (
			'#' +
			Math.floor(Math.random() * 16777215)
				.toString(16)
				.padStart(6, '0')
		);
	}

	function randomSemanticHex(
		hueCenter: number,
		hueSpread: number,
		lRange: [number, number],
		cRange: [number, number]
	): string {
		const h = hueCenter + (Math.random() - 0.5) * hueSpread;
		const l = lRange[0] + Math.random() * (lRange[1] - lRange[0]);
		const c = cRange[0] + Math.random() * (cRange[1] - cRange[0]);
		return oklchToHex({ l, c, h: ((h % 360) + 360) % 360 });
	}

	// ── State ──────────────────────────────────────────────────────────────────

	let inputs = $state<PaletteInputs>({ ...DEFAULT_INPUTS });

	/*
	 * The React original debounced this behind a 50ms `setTimeout` because every
	 * `SketchPicker` drag fired a state update that re-rendered both previews.
	 * `generateFullPalette` is pure arithmetic over ~20 colours, and Svelte
	 * updates only the inline styles that actually changed, so the debounce —
	 * and the visible lag it introduced on every edit — is not needed.
	 */
	let palette = $derived(generateFullPalette(inputs));

	const semanticFields = [
		{ key: 'primary', label: 'Primary' },
		{ key: 'secondary', label: 'Secondary' },
		{ key: 'accent', label: 'Accent' }
	] as const;

	const statusFields = [
		{ key: 'info', label: 'Info' },
		{ key: 'success', label: 'Success' },
		{ key: 'warning', label: 'Warning' },
		{ key: 'error', label: 'Error' }
	] as const;

	function handleRandomAll() {
		inputs = {
			...inputs,
			baseHue: Math.floor(Math.random() * 360),
			// Rolled too, or every random theme comes back on the same near-white
			// surface. Bounded well short of 1: past ~0.7 the surfaces stop reading
			// as chrome and start competing with the curves.
			baseSaturation: 0.1 + Math.random() * 0.5,
			primary: randomHex(),
			secondary: randomHex(),
			accent: randomSemanticHex(280, 60, [0.4, 0.55], [0.01, 0.06]),
			info: randomSemanticHex(220, 40, [0.6, 0.75], [0.12, 0.2]),
			success: randomSemanticHex(130, 40, [0.65, 0.8], [0.15, 0.25]),
			warning: randomSemanticHex(75, 30, [0.7, 0.85], [0.14, 0.22]),
			error: randomSemanticHex(15, 20, [0.55, 0.7], [0.18, 0.26])
		};
	}

	function clamp(min: number, value: number, max: number): number {
		return Math.max(min, Math.min(max, value));
	}

	/**
	 * Every base-tone control is a percentage in the UI and a 0–1 fraction in the
	 * palette, except the hue. `set` takes the already-converted value.
	 */
	function setNumber(raw: number, min: number, max: number, set: (value: number) => void) {
		if (Number.isNaN(raw)) return;
		set(clamp(min, raw, max));
	}

	const pct = (value: number) => Math.round(value * 100);

	// ── Slider track gradients ─────────────────────────────────────────────────
	/*
	 * Each track is painted with the colours that slider position would actually
	 * produce, by asking `generateBaseScale` for the ends of its own range. It
	 * costs a few gamut bisections per keystroke and removes the guesswork from
	 * controls whose effect is otherwise invisible until you release them.
	 */

	function gradient(...stops: string[]): string {
		return `linear-gradient(to right, ${stops.join(', ')})`;
	}

	function lightBase(saturation: number, lightness: number) {
		return generateBaseScale(inputs.baseHue, saturation, lightness, inputs.baseLightnessDark).light;
	}

	function darkBase(lightness: number) {
		return generateBaseScale(
			inputs.baseHue,
			inputs.baseSaturation,
			inputs.baseLightnessLight,
			lightness
		).dark;
	}

	const HUE_TRACK = gradient(
		'hsl(0, 70%, 60%)',
		'hsl(60, 70%, 60%)',
		'hsl(120, 70%, 60%)',
		'hsl(180, 70%, 60%)',
		'hsl(240, 70%, 60%)',
		'hsl(300, 70%, 60%)',
		'hsl(360, 70%, 60%)'
	);

	// Sampled at `base-300` rather than `base-100`: the tint is the same share of
	// the gamut at every step of the scale, but only the darkest surface has
	// enough room to show it at a glance.
	let saturationTrack = $derived(
		gradient(
			oklchToCssString(lightBase(0, inputs.baseLightnessLight).base300),
			oklchToCssString(lightBase(0.5, inputs.baseLightnessLight).base300),
			oklchToCssString(lightBase(1, inputs.baseLightnessLight).base300)
		)
	);

	let lightnessLightTrack = $derived(
		gradient(
			oklchToCssString(lightBase(inputs.baseSaturation, BASE_LIGHTNESS_LIGHT_RANGE[0]).base100),
			oklchToCssString(lightBase(inputs.baseSaturation, BASE_LIGHTNESS_LIGHT_RANGE[1]).base100)
		)
	);

	let lightnessDarkTrack = $derived(
		gradient(
			oklchToCssString(darkBase(BASE_LIGHTNESS_DARK_RANGE[0]).base100),
			oklchToCssString(darkBase(BASE_LIGHTNESS_DARK_RANGE[1]).base100)
		)
	);

	function handleExport() {
		const css = generateThemeCssContent(palette.light, palette.dark);
		const blob = new Blob([css], { type: 'text/css' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = 'theme.css';
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}
</script>

{#snippet baseSlider(
	id: string,
	label: string,
	min: number,
	max: number,
	value: number,
	track: string,
	set: (value: number) => void
)}
	<section class="tgSliderField">
		<label for={id}>{label}</label>
		<div class="tgSliderRow">
			<input
				{id}
				type="range"
				{min}
				{max}
				step="1"
				class="tgSlider"
				style="--tg-track: {track}"
				{value}
				oninput={(e) => setNumber(e.currentTarget.valueAsNumber, min, max, set)}
			/>
			<input
				type="number"
				aria-label={label}
				{min}
				{max}
				step="1"
				class="tgNumberInput"
				{value}
				oninput={(e) => setNumber(e.currentTarget.valueAsNumber, min, max, set)}
			/>
		</div>
	</section>
{/snippet}

<div class="tgContainer">
	<div class="tgTools">
		<h4>{t('Base Tone')}</h4>
		<p class="tgDescription">
			{t(
				'Controls the base palette (backgrounds, text, borders). Hue and saturation tint every surface; the surface sliders set how light each mode starts. A near-white surface can only hold a faint tint, so lower Light Surface to push saturation further.'
			)}
		</p>
		{@render baseSlider(
			'tgBaseHue',
			t('Base Hue'),
			0,
			360,
			inputs.baseHue,
			HUE_TRACK,
			(v) => (inputs.baseHue = v)
		)}
		{@render baseSlider(
			'tgBaseSaturation',
			t('Base Saturation'),
			0,
			100,
			pct(inputs.baseSaturation),
			saturationTrack,
			(v) => (inputs.baseSaturation = v / 100)
		)}
		{@render baseSlider(
			'tgLightSurface',
			t('Light Surface'),
			pct(BASE_LIGHTNESS_LIGHT_RANGE[0]),
			pct(BASE_LIGHTNESS_LIGHT_RANGE[1]),
			pct(inputs.baseLightnessLight),
			lightnessLightTrack,
			(v) => (inputs.baseLightnessLight = v / 100)
		)}
		{@render baseSlider(
			'tgDarkSurface',
			t('Dark Surface'),
			pct(BASE_LIGHTNESS_DARK_RANGE[0]),
			pct(BASE_LIGHTNESS_DARK_RANGE[1]),
			pct(inputs.baseLightnessDark),
			lightnessDarkTrack,
			(v) => (inputs.baseLightnessDark = v / 100)
		)}

		<div class="tgSectionHeader">
			<h4>{t('Semantic Colors')}</h4>
			<button type="button" class="ceBtn tgSourceColorRandomizerButton" onclick={handleRandomAll}>
				{t('Random All')}
			</button>
		</div>
		<p class="tgDescription">
			{t(
				'Pick colors for each role. Content (text-on-color) and dark mode variants are auto-generated.'
			)}
		</p>

		{#each semanticFields as { key, label } (key)}
			<ColorField {label} bind:value={inputs[key]} />
		{/each}

		<h4>{t('Status Colors')}</h4>
		{#each statusFields as { key, label } (key)}
			<ColorField {label} bind:value={inputs[key]} />
		{/each}

		<button type="button" class="ceBtn ceBtnPrimary tgExportButton" onclick={handleExport}>
			<Icon name="download" />
			{t('Export theme.css')}
		</button>
	</div>
	<div class="tgPreview">
		<DummyGraphPage colorMode="light" theme={palette.light} />
		<DummyGraphPage colorMode="dark" theme={palette.dark} />
	</div>
</div>

<style>
	/*
	 * Scoped: every class here is used by this component alone. The chrome —
	 * panels, buttons, inputs — comes from `styles/tools.css` via the shared
	 * class names, so what is left is only the layout and the hue slider.
	 */
	.tgContainer {
		display: flex;
		flex-wrap: wrap;
		gap: 1.25rem;
	}

	/*
	 * `min()` and not a bare `19rem`: a flex item's `min-width` is a hard floor,
	 * so on a viewport narrower than the floor the panel — and most visibly the
	 * randomiser sitting at its right edge — spills out of the page rather than
	 * shrinking. The `100%` arm hands the floor back below that width.
	 */
	.tgTools {
		flex: 1;
		min-width: min(19rem, 100%);
		display: flex;
		flex-direction: column;
		gap: 0.875rem;
		padding: 1rem;
		border: 1px solid var(--tool-hairline);
		border-radius: var(--tool-radius);
		background: var(--tool-surface);
		align-self: flex-start;
	}

	.tgTools h4 {
		margin: 0.5rem 0 0;
		padding-bottom: 0.375rem;
		border-bottom: 1px solid var(--tool-hairline);
		font-size: var(--sl-text-sm);
		font-weight: 600;
		color: var(--tool-text-strong);
	}

	.tgTools h4:first-child {
		margin-top: 0;
	}

	.tgDescription {
		margin: -0.5rem 0 0;
		font-size: var(--sl-text-xs);
		color: var(--tool-text-muted);
		line-height: 1.5;
	}

	/*
	 * The randomiser is a section action, not a Primary one — it rerolls the base
	 * hue and saturation as well as all seven swatches — so it sits on the
	 * heading rather than beside the first field. That is also the only place it
	 * fits: sharing Primary's row squeezed the three L/C/H boxes until their
	 * values truncated, and on a phone it left the button nowhere to go but off
	 * the edge of the panel. It wraps under the heading if a locale's label is
	 * long enough to need it.
	 */
	.tgSectionHeader {
		display: flex;
		flex-wrap: wrap;
		align-items: baseline;
		justify-content: space-between;
		gap: 0.5rem 0.75rem;
		margin-top: 0.5rem;
		padding-bottom: 0.375rem;
		border-bottom: 1px solid var(--tool-hairline);
	}

	/* The rule above already draws the divider for the whole row. */
	.tgSectionHeader h4 {
		margin: 0;
		padding-bottom: 0;
		border-bottom: none;
	}

	.tgSourceColorRandomizerButton {
		flex: 0 0 auto;
	}

	.tgPreview {
		flex: 2;
		min-width: min(25rem, 100%);
		display: flex;
		flex-direction: column;
		gap: 1.25rem;
	}

	/* ── Base tone controls ──────────────────────────────────────────────────── */

	.tgSliderField {
		display: flex;
		flex-direction: column;
		gap: 0.375rem;
		width: 100%;
	}

	.tgSliderField label {
		font-size: var(--sl-text-xs);
		font-weight: 500;
		color: var(--tool-text-strong);
	}

	.tgSliderRow {
		display: flex;
		align-items: center;
		gap: 0.625rem;
		width: 100%;
	}

	/*
	 * Each track is painted by its own control with the colours that position
	 * produces — the one place in the tools where a raw colour is the content
	 * rather than the chrome, so it is exempt from the "tokens only" rule. The
	 * thumb still is not: it borrows the surface and border tokens so it reads
	 * correctly against either theme, and a checkerboard behind the track keeps
	 * a near-white surface visible on the light page.
	 */
	.tgSlider {
		-webkit-appearance: none;
		appearance: none;
		flex: 1;
		min-width: 0;
		height: 0.5rem;
		border-radius: 999px;
		border: 1px solid var(--tool-border);
		background: var(--tg-track);
	}

	.tgSlider::-webkit-slider-thumb {
		-webkit-appearance: none;
		appearance: none;
		width: 1rem;
		height: 1rem;
		border-radius: 50%;
		background: var(--tool-surface);
		border: 2px solid var(--tool-text-muted);
		cursor: pointer;
		box-shadow: var(--sl-shadow-sm);
	}

	.tgSlider::-moz-range-thumb {
		width: 1rem;
		height: 1rem;
		border-radius: 50%;
		background: var(--tool-surface);
		border: 2px solid var(--tool-text-muted);
		cursor: pointer;
		box-shadow: var(--sl-shadow-sm);
	}

	.tgExportButton {
		width: 100%;
		margin-top: 0.5rem;
	}
</style>
