import { paraglideVitePlugin } from '@inlang/paraglide-js';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vitest/config';
import type { Plugin } from 'vite';
import { playwright } from '@vitest/browser-playwright';
import { sveltekit } from '@sveltejs/kit/vite';
import defaultsPlugin from './vite-plugin-defaults.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const pkg = JSON.parse(
	readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8')
);

/**
 * turboEQ's wasm is ported from AutoEq (MIT) and SciPy (BSD-3-Clause), whose
 * licences require their notices to accompany every copy of the binary. The
 * file goes beside the wasm, so it travels wherever `_app/` is hosted — the
 * CDN build included.
 */
function turboEqNotice(): Plugin {
	return {
		name: 'turboeq-notice',
		apply: 'build',
		generateBundle() {
			if (this.environment.name !== 'client') return;
			this.emitFile({
				type: 'asset',
				fileName: '_app/immutable/workers/assets/NOTICE-turboeq.txt',
				source: readFileSync(
					fileURLToPath(new URL('./node_modules/@potatosalad775/turboeq/NOTICE', import.meta.url)),
					'utf-8'
				)
			});
		}
	};
}

export default defineConfig({
	define: {
		__APP_VERSION__: JSON.stringify(pkg.version)
	},
	plugins: [
		tailwindcss(),
		sveltekit(),
		// Keep these options in sync with the `i18n:compile` script in package.json, which
		// compiles the same output for `npm run check` — svelte-check does not run Vite, so
		// without it $lib/paraglide/* has no type declarations on a fresh clone.
		paraglideVitePlugin({
			project: './project.inlang',
			outdir: './src/lib/paraglide',
			strategy: ['localStorage', 'preferredLanguage', 'baseLocale']
		}),
		defaultsPlugin(),
		turboEqNotice()
	],
	worker: {
		format: 'es'
	},
	// turboEQ is only reached through a dynamic import inside the AutoEQ worker,
	// which the optimizer's startup scan never crawls. Discovered later, it forces
	// a re-optimize and a full reload: in dev that reloads the page the first time
	// the Equalizer tab opens, and in browser tests it breaks whichever spec file
	// is importing at that moment ("Cannot read properties of undefined (reading
	// 'config')"). It is plain ESM with no dependencies, so there is nothing to gain
	// from pre-bundling it anyway.
	optimizeDeps: { exclude: ['@potatosalad775/turboeq'] },
	test: {
		expect: { requireAssertions: true },
		coverage: {
			provider: 'v8',
			// `include` is what makes the number honest: it measures every matching
			// file, not just the ones some test happens to import. Without it an
			// untested module vanishes from the denominator instead of showing up as
			// the 0% it is — the 25 device-peq handler/connector modules that lived
			// here before the eqcaps bridge made the figure ~10 points optimistic.
			include: ['src/**/*.{ts,svelte}'],
			exclude: [
				// Generated by the Paraglide Vite plugin and gitignored. Counting it added
				// ~3800 machine-written statements, a third of the total, and dragged the
				// reported figure well below what the hand-written source actually is.
				'src/lib/paraglide/**',
				'src/lib/types/**', // type-only, no runtime statements
				'src/**/*.{spec,test}.ts',
				'src/**/*.d.ts',
				'src/routes/**', // +layout/+page shells; exercised by the AppShell boot tests
				'src/hooks*.ts',
				'src/lib/components/layout/app-boot-harness.ts' // test infrastructure
			],
			reporter: ['text', 'text-summary', 'html', 'json-summary'],
			// A ratchet, not a target. These are the measured numbers at the time the
			// honest config landed, rounded down. Raise them when coverage improves;
			// never lower them to make a red run go green.
			//
			// Each sits ~1 point under the measured figure. Repeated runs drift by a
			// few hundredths of a percent — browser-mode specs race a little over
			// which branches they reach — so a threshold pinned to the exact number
			// would flap red without anything changing.
			//
			// Last measured after the device PEQ bridge moved to eqcaps (its ~9k lines
			// of untested handlers left the denominator): 84.06 / 74.21 / 86.05 / 85.90,
			// up from 71.00 / 64.09 / 75.90 / 70.66. All four are raised.
			thresholds: {
				statements: 83,
				branches: 73,
				functions: 85,
				lines: 84
			}
		},
		projects: [
			{
				extends: './vite.config.ts',
				// Component tests mount real UI, which pulls in bits-ui. Pre-bundling it
				// gives it its own copy of the Svelte client runtime, and a component
				// rendered by one instance can't read the other's context — Accordion
				// dies with "Cannot read properties of null". Serving it unbundled lets
				// its bare `svelte` imports resolve through the same deduped copy the app
				// uses. Only needed for tests; dev and build pre-bundle it normally.
				optimizeDeps: { exclude: ['bits-ui'] },
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						// Browser mode defaults to a 414x896 iframe, which is below the
						// `appStore.isMobile` threshold (innerWidth < 1000) — so without this
						// every component test silently runs the mobile layout. Default to
						// desktop and let mobile tests opt in via `page.viewport()`.
						viewport: { width: 1280, height: 800 },
						// Vitest 5 made text locators exact by default. The specs were written
						// against substring matching (a hint inside "Label — hint", a label
						// inside a longer curve name), so keep it.
						locators: { exact: false },
						instances: [{ browser: 'chromium', headless: true }]
					},
					// Pins the UI language. Without it the suite renders in whatever
					// locale the developer's machine uses and every English-string query
					// fails on a timeout. See the file for the full story.
					setupFiles: ['./src/test-setup.client.ts'],
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**']
				}
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
