import { paraglideVitePlugin } from '@inlang/paraglide-js';
import tailwindcss from '@tailwindcss/vite';
import { defineConfig } from 'vitest/config';
import { playwright } from '@vitest/browser-playwright';
import { sveltekit } from '@sveltejs/kit/vite';
import defaultsPlugin from './vite-plugin-defaults.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const pkg = JSON.parse(
	readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8')
);

export default defineConfig({
	define: {
		__APP_VERSION__: JSON.stringify(pkg.version)
	},
	plugins: [
		tailwindcss(),
		sveltekit(),
		// Keep these options in sync with the `i18n:compile` script in package.json, which
		// compiles the same output for `npm run check` — svelte-check does not run Vite, so
		// without it $lib/paraglide/* has no type declarations on a fresh clone.
		paraglideVitePlugin({
			project: './project.inlang',
			outdir: './src/lib/paraglide',
			strategy: ['localStorage', 'preferredLanguage', 'baseLocale']
		}),
		defaultsPlugin()
	],
	worker: {
		format: 'es'
	},
	test: {
		expect: { requireAssertions: true },
		coverage: {
			provider: 'v8',
			// `include` is what makes the number honest: it measures every matching
			// file, not just the ones some test happens to import. Without it the 25
			// device-peq handler/connector modules — the least reviewable code in the
			// repo — vanish from the denominator instead of showing up as the 0% they
			// are, which made the reported figure ~10 points optimistic.
			include: ['src/**/*.{ts,svelte}'],
			exclude: [
				// Generated by the Paraglide Vite plugin and gitignored. Counting it added
				// ~3800 machine-written statements, a third of the total, and dragged the
				// reported figure well below what the hand-written source actually is.
				'src/lib/paraglide/**',
				'src/lib/types/**', // type-only, no runtime statements
				'src/**/*.{spec,test}.ts',
				'src/**/*.d.ts',
				'src/routes/**', // +layout/+page shells; exercised by the AppShell boot tests
				'src/hooks*.ts',
				'src/lib/components/layout/app-boot-harness.ts' // test infrastructure
			],
			reporter: ['text', 'text-summary', 'html', 'json-summary'],
			// A ratchet, not a target. These are the measured numbers at the time the
			// honest config landed, rounded down. Raise them when coverage improves;
			// never lower them to make a red run go green.
			thresholds: {
				statements: 57,
				branches: 51,
				functions: 58,
				lines: 59
			}
		},
		projects: [
			{
				extends: './vite.config.ts',
				// Component tests mount real UI, which pulls in bits-ui. Pre-bundling it
				// gives it its own copy of the Svelte client runtime, and a component
				// rendered by one instance can't read the other's context — Accordion
				// dies with "Cannot read properties of null". Serving it unbundled lets
				// its bare `svelte` imports resolve through the same deduped copy the app
				// uses. Only needed for tests; dev and build pre-bundle it normally.
				optimizeDeps: { exclude: ['bits-ui'] },
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						// Browser mode defaults to a 414x896 iframe, which is below the
						// `appStore.isMobile` threshold (innerWidth < 1000) — so without this
						// every component test silently runs the mobile layout. Default to
						// desktop and let mobile tests opt in via `page.viewport()`.
						viewport: { width: 1280, height: 800 },
						instances: [{ browser: 'chromium', headless: true }]
					},
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**']
				}
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}']
				}
			}
		]
	}
});
